services:
  web:
    image: node:22
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c "npm ci && npm run dev -- --host"
    environment:
      - NODE_ENV=development
    ports:
      - "5173:5173"
    tty: true